apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ .Values.appName}}
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: {{ .Values.appName}}
  template: 
    metadata: 
      labels: 
        app: {{ .Values.appName}}
    spec: 
      containers: 
      - name: {{ .Values.container.name}}
        image: {{ .Values.container.image}}
        ports: 
          - containerPort: {{ .Values.ports.containerPort}}    
         
       

