apiVersion: v1
kind: Service 
metadata: 
  name: {{ .Values.serviceName}}
spec: 
  selector: 
    app: {{ .Values.appName}}
  type: NodePort
  ports: 
  - protocol: TCP
    port: {{ .Values.ports.port}}
    targetPort: {{ .Values.ports.targetPort}}
    nodePort: {{ .Values.ports.nodePort}} 